const STRIVER_DSA_SHEET = [

  { title: "Two Sum", link: "https://leetcode.com/problems/two-sum/" },
  { title: "Two Sum", link: "https://leetcode.com/problems/two-sum/" },
  { title: "Longest Substring Without Repeating Characters", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { title: "Merge Intervals", link: "https://leetcode.com/problems/merge-intervals/" },
  { title: "Reverse Linked List", link: "https://leetcode.com/problems/reverse-linked-list/" },
  { title: "Detect Cycle in a Directed Graph", link: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1" },
  { title: "Sort Colors", link: "https://leetcode.com/problems/sort-colors/" },
  { title: "N-Queens", link: "https://leetcode.com/problems/n-queens/" },
  { title: "Trapping Rain Water", link: "https://leetcode.com/problems/trapping-rain-water/" },
  { title: "Longest Palindromic Substring", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
  { title: "Median of Two Sorted Arrays", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { title: "Kth Largest Element", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { title: "Add Two Numbers", link: "https://leetcode.com/problems/add-two-numbers/" },
  { title: "Remove Nth Node From End of List", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { title: "Merge Two Sorted Lists", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { title: "Swap Nodes in Pairs", link: "https://leetcode.com/problems/swap-nodes-in-pairs/" },
  { title: "Rotate List", link: "https://leetcode.com/problems/rotate-list/" },
  { title: "Reverse Nodes in k-Group", link: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  { title: "Palindrome Linked List", link: "https://leetcode.com/problems/palindrome-linked-list/" },
  { title: "Flatten a Linked List", link: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1" },
  { title: "LRU Cache", link: "https://leetcode.com/problems/lru-cache/" },
  { title: "Intersection of Two Linked Lists", link: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
  { title: "Maximum Subarray", link: "https://leetcode.com/problems/maximum-subarray/" },
  { title: "Best Time to Buy and Sell Stock", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { title: "Best Time to Buy and Sell Stock II", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/" },
  { title: "Best Time to Buy and Sell Stock III", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/" },
  { title: "Product of Array Except Self", link: "https://leetcode.com/problems/product-of-array-except-self/" },
  { title: "Find the Duplicate Number", link: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { title: "Set Matrix Zeroes", link: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { title: "Spiral Matrix", link: "https://leetcode.com/problems/spiral-matrix/" },
  { title: "Rotate Image", link: "https://leetcode.com/problems/rotate-image/" },
  { title: "Search a 2D Matrix", link: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { title: "Search in Rotated Sorted Array", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { title: "Find First and Last Position of Element in Sorted Array", link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
  { title: "Sqrt(x)", link: "https://leetcode.com/problems/sqrtx/" },
  { title: "Valid Sudoku", link: "https://leetcode.com/problems/valid-sudoku/" },
  { title: "First Missing Positive", link: "https://leetcode.com/problems/first-missing-positive/" },
  { title: "Largest Rectangle in Histogram", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  { title: "Sliding Window Maximum", link: "https://leetcode.com/problems/sliding-window-maximum/" },
  { title: "Longest Valid Parentheses", link: "https://leetcode.com/problems/longest-valid-parentheses/" },
  { title: "Valid Parentheses", link: "https://leetcode.com/problems/valid-parentheses/" },
  { title: "Next Permutation", link: "https://leetcode.com/problems/next-permutation/" },
  { title: "Permutations", link: "https://leetcode.com/problems/permutations/" },
  { title: "Subsets", link: "https://leetcode.com/problems/subsets/" },
  { title: "Combination Sum", link: "https://leetcode.com/problems/combination-sum/" },
  { title: "Word Search", link: "https://leetcode.com/problems/word-search/" },
  { title: "Generate Parentheses", link: "https://leetcode.com/problems/generate-parentheses/" },
  { title: "Letter Combinations of a Phone Number", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
  { title: "Palindrome Partitioning", link: "https://leetcode.com/problems/palindrome-partitioning/" },
  { title: "Subset Sum Problem", link: "https://practice.geeksforgeeks.org/problems/subset-sum-problem/1" },
  { title: "Kth Smallest Element in a BST", link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { title: "Validate Binary Search Tree", link: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { title: "Binary Tree Inorder Traversal", link: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
  { title: "Binary Tree Preorder Traversal", link: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
  { title: "Binary Tree Postorder Traversal", link: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
  { title: "Binary Tree Level Order Traversal", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { title: "Maximum Depth of Binary Tree", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { title: "Minimum Depth of Binary Tree", link: "https://leetcode.com/problems/minimum-depth-of-binary-tree/" },
  { title: "Symmetric Tree", link: "https://leetcode.com/problems/symmetric-tree/" },
  { title: "Path Sum", link: "https://leetcode.com/problems/path-sum/" },
  { title: "Construct Binary Tree from Preorder and Inorder Traversal", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { title: "Lowest Common Ancestor of a Binary Tree", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
  { title: "Binary Tree Maximum Path Sum", link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { title: "Diameter of Binary Tree", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
  { title: "Invert Binary Tree", link: "https://leetcode.com/problems/invert-binary-tree/" },
  { title: "Flatten Binary Tree to Linked List", link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
  { title: "Top View of Binary Tree", link: "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1" },
  { title: "Bottom View of Binary Tree", link: "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1" },
  { title: "ZigZag Level Order Traversal", link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
  { title: "Boundary Traversal of Binary Tree", link: "https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1" },
  { title: "Clone a Binary Tree", link: "https://practice.geeksforgeeks.org/problems/clone-a-binary-tree/1" },
  { title: "Serialize and Deserialize Binary Tree", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
  { title: "Course Schedule", link: "https://leetcode.com/problems/course-schedule/" },
  { title: "Course Schedule II", link: "https://leetcode.com/problems/course-schedule-ii/" },
  { title: "Topological Sort", link: "https://practice.geeksforgeeks.org/problems/topological-sort/1" },
  { title: "Find if Path Exists in Graph", link: "https://leetcode.com/problems/find-if-path-exists-in-graph/" },
  { title: "Number of Islands", link: "https://leetcode.com/problems/number-of-islands/" },
  { title: "Flood Fill", link: "https://leetcode.com/problems/flood-fill/" },
  { title: "Surrounded Regions", link: "https://leetcode.com/problems/surrounded-regions/" },
  { title: "Word Ladder", link: "https://leetcode.com/problems/word-ladder/" },
  { title: "Shortest Path in Binary Matrix", link: "https://leetcode.com/problems/shortest-path-in-binary-matrix/" },
  { title: "Alien Dictionary", link: "https://practice.geeksforgeeks.org/problems/alien-dictionary/1" },
  { title: "Cheapest Flights Within K Stops", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
  { title: "Minimum Spanning Tree", link: "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
  { title: "Kruskal's Algorithm", link: "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
  { title: "Prim's Algorithm", link: "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
  { title: "Dijkstra's Algorithm", link: "https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1" },
  { title: "Bellman-Ford Algorithm", link: "https://practice.geeksforgeeks.org/problems/negative-weight-cycle/1" },
  { title: "Floyd Warshall Algorithm", link: "https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall/1" },
  { title: "Find the City With the Smallest Number of Neighbors", link: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/" },
  { title: "Bipartite Graph", link: "https://practice.geeksforgeeks.org/problems/bipartite-graph/1" },
  { title: "Disjoint Set (Union-Find)", link: "https://practice.geeksforgeeks.org/problems/disjoint-set-union-find/1" },
  { title: "Rotten Oranges", link: "https://practice.geeksforgeeks.org/problems/rotten-oranges/1" },
  { title: "Minimum Time to Collect All Apples", link: "https://leetcode.com/problems/minimum-time-to-collect-all-apples-in-a-tree/" },
  { title: "Clone Graph", link: "https://leetcode.com/problems/clone-graph/" },
  { title: "0/1 Knapsack Problem", link: "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/1" },
  { title: "Fractional Knapsack", link: "https://practice.geeksforgeeks.org/problems/fractional-knapsack/1" },
  { title: "Coin Change", link: "https://leetcode.com/problems/coin-change/" },
  { title: "Coin Change 2", link: "https://leetcode.com/problems/coin-change-2/" },
  { title: "Longest Common Subsequence", link: "https://leetcode.com/problems/longest-common-subsequence/" },
  { title: "Longest Increasing Subsequence", link: "https://leetcode.com/problems/longest-increasing-subsequence/" },
  { title: "Edit Distance", link: "https://leetcode.com/problems/edit-distance/" },
  { title: "Minimum Path Sum", link: "https://leetcode.com/problems/minimum-path-sum/" },
  { title: "Unique Paths", link: "https://leetcode.com/problems/unique-paths/" },
  { title: "Unique Paths II", link: "https://leetcode.com/problems/unique-paths-ii/" },
  { title: "Climbing Stairs", link: "https://leetcode.com/problems/climbing-stairs/" },
  { title: "House Robber", link: "https://leetcode.com/problems/house-robber/" },
  { title: "House Robber II", link: "https://leetcode.com/problems/house-robber-ii/" },
  { title: "Maximum Product Subarray", link: "https://leetcode.com/problems/maximum-product-subarray/" },
  { title: "Word Break", link: "https://leetcode.com/problems/word-break/" },
  { title: "Palindrome Partitioning II", link: "https://leetcode.com/problems/palindrome-partitioning-ii/" },
  { title: "Matrix Chain Multiplication", link: "https://practice.geeksforgeeks.org/problems/matrix-chain-multiplication/1" },
  { title: "Partition Equal Subset Sum", link: "https://leetcode.com/problems/partition-equal-subset-sum/" },
  { title: "Target Sum", link: "https://leetcode.com/problems/target-sum/" },
  { title: "Burst Balloons", link: "https://leetcode.com/problems/burst-balloons/" },
  { title: "Longest Common Substring", link: "https://practice.geeksforgeeks.org/problems/longest-common-substring/1" },
  { title: "Scramble String", link: "https://leetcode.com/problems/scramble-string/" },
  { title: "Egg Dropping Puzzle", link: "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/1" },
  { title: "Wildcard Matching", link: "https://leetcode.com/problems/wildcard-matchinging/" },
  { title: "Regular Expression Matching", link: "https://leetcode.com/problems/regular-expression-matchinging/" },
  { title: "Maximal Square", link: "https://leetcode.com/problems/maximal-square/" },
  { title: "Count Square Submatrices with All Ones", link: "https://leetcode.com/problems/count-square-submatrices-with-all-ones/" },
  { title: "Minimum Cost to Cut a Stick", link: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/" },
  { title: "Activity Selection Problem", link: "https://practice.geeksforgeeks.org/problems/activity-selection/1" },
  { title: "Job Sequencing Problem", link: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem/1" },
  { title: "Huffman Coding", link: "https://practice.geeksforgeeks.org/problems/huffman-encoding/1" },
  { title: "Minimum Platforms", link: "https://practice.geeksforgeeks.org/problems/minimum-platforms/1" },
  { title: "Fractional Knapsack", link: "https://practice.geeksforgeeks.org/problems/fractional-knapsack/1" },
  { title: "Meeting Rooms", link: "https://leetcode.com/problems/meeting-rooms/" },
  { title: "Meeting Rooms II", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
  { title: "Non-overlapping Intervals", link: "https://leetcode.com/problems/non-overlapping-intervals/" },
  { title: "Minimum Number of Arrows to Burst Balloons", link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/" },
  { title: "Gas Station", link: "https://leetcode.com/problems/gas-station/" },
  { title: "Candy", link: "https://leetcode.com/problems/candy/" },
  { title: "Jump Game", link: "https://leetcode.com/problems/jump-game/" },
  { title: "Jump Game II", link: "https://leetcode.com/problems/jump-game-ii/" },
  { title: "Minimum Cost to Reach Destination", link: "https://practice.geeksforgeeks.org/problems/minimum-cost-to-reach-destination-in-time/1" },
  { title: "Queue Reconstruction by Height", link: "https://leetcode.com/problems/queue-reconstruction-by-height/" },
  { title: "Task Scheduler", link: "https://leetcode.com/problems/task-scheduler/" },
  { title: "Single Number", link: "https://leetcode.com/problems/single-number/" },
  { title: "Single Number II", link: "https://leetcode.com/problems/single-number-ii/" },
  { title: "Single Number III", link: "https://leetcode.com/problems/single-number-iii/" },
  { title: "Missing Number", link: "https://leetcode.com/problems/missing-number/" },
  { title: "Count Set Bits", link: "https://practice.geeksforgeeks.org/problems/set-bits/1" },
  { title: "Power of Two", link: "https://leetcode.com/problems/power-of-two/" },
  { title: "Reverse Bits", link: "https://leetcode.com/problems/reverse-bits/" },
  { title: "Number of 1 Bits", link: "https://leetcode.com/problems/number-of-1-bits/" },
  { title: "Divide Two Integers", link: "https://leetcode.com/problems/divide-two-integers/" },
  { title: "Bitwise AND of Numbers Range", link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/" },
  { title: "Majority Element", link: "https://leetcode.com/problems/majority-element/" },
  { title: "Majority Element II", link: "https://leetcode.com/problems/majority-element-ii/" },
  { title: "Find Peak Element", link: "https://leetcode.com/problems/find-peak-element/" },
  { title: "Kth Largest Element in an Array", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { title: "Sort List", link: "https://leetcode.com/problems/sort-list/" },
  { title: "Merge k Sorted Lists", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { title: "QuickSort", link: "https://practice.geeksforgeeks.org/problems/quick-sort/1" },
  { title: "Merge Sort", link: "https://practice.geeksforgeeks.org/problems/merge-sort/1" },
  { title: "Heap Sort", link: "https://practice.geeksforgeeks.org/problems/heap-sort/1" },
  { title: "Kth Smallest Element in a Sorted Matrix", link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/" },
  { title: "Find Median from Data Stream", link: "https://leetcode.com/problems/find-median-from-data-stream/" },
  { title: "Top K Frequent Elements", link: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { title: "Top K Frequent Words", link: "https://leetcode.com/problems/top-k-frequent-words/" },
  { title: "Sort Characters By Frequency", link: "https://leetcode.com/problems/sort-characters-by-frequency/" },
  { title: "K Closest Points to Origin", link: "https://leetcode.com/problems/k-closest-points-to-origin/" },
  { title: "Implement Stack using Queues", link: "https://leetcode.com/problems/implement-stack-using-queues/" },
  { title: "Implement Queue using Stacks", link: "https://leetcode.com/problems/implement-queue-using-stacks/" },
  { title: "Min Stack", link: "https://leetcode.com/problems/min-stack/" },
  { title: "Design Circular Queue", link: "https://leetcode.com/problems/design-circular-queue/" },
  { title: "Evaluate Reverse Polish Notation", link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
  { title: "Decode String", link: "https://leetcode.com/problems/decode-string/" },
  { title: "Daily Temperatures", link: "https://leetcode.com/problems/daily-temperatures/" },
  { title: "Next Greater Element I", link: "https://leetcode.com/problems/next-greater-element-i/" },
  { title: "Next Greater Element II", link: "https://leetcode.com/problems/next-greater-element-ii/" },
  { title: "Remove K Digits", link: "https://leetcode.com/problems/remove-k-digits/" },
  { title: "Asteroid Collision", link: "https://leetcode.com/problems/asteroid-collision/" },
  { title: "Implement Trie (Prefix Tree)", link: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
  { title: "Design Add and Search Words Data Structure", link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
  { title: "Word Search II", link: "https://leetcode.com/problems/word-search-ii/" },
  { title: "Longest Word in Dictionary", link: "https://leetcode.com/problems/longest-word-in-dictionary/" },
  { title: "Maximum Frequency Stack", link: "https://leetcode.com/problems/maximum-frequency-stack/" },
  { title: "Design Twitter", link: "https://leetcode.com/problems/design-twitter/" },
  { title: "LRU Cache", link: "https://leetcode.com/problems/lru-cache/" },
  { title: "LFU Cache", link: "https://leetcode.com/problems/lfu-cache/" },
  { title: "Design Tic-Tac-Toe", link: "https://leetcode.com/problems/design-tic-tac-toe/" },
  { title: "Design Snake Game", link: "https://leetcode.com/problems/design-snake-game/" },
  { title: "Insert Delete GetRandom O(1)", link: "https://leetcode.com/problems/insert-delete-getrandom-o1/" },
  { title: "Design Underground System", link: "https://leetcode.com/problems/design-underground-system/" },
  { title: "Design Browser History", link: "https://leetcode.com/problems/design-browser-history/" },
  { title: "Design Parking System", link: "https://leetcode.com/problems/design-parking-system/" },
  { title: "Design HashMap", link: "https://leetcode.com/problems/design-hashmap/" },
  { title: "Design HashSet", link: "https://leetcode.com/problems/design-hashset/" },
  { title: "Reverse Integer", link: "https://leetcode.com/problems/reverse-integer/" },
  { title: "String to Integer (atoi)", link: "https://leetcode.com/problems/string-to-integer-atoi/" },
  { title: "Roman to Integer", link: "https://leetcode.com/problems/roman-to-integer/" },
  { title: "Integer to Roman", link: "https://leetcode.com/problems/integer-to-roman/" },
  { title: "ZigZag Conversion", link: "https://leetcode.com/problems/zigzag-conversion/" },
  { title: "Text Justification", link: "https://leetcode.com/problems/text-justification/" },
  { title: "Group Anagrams", link: "https://leetcode.com/problems/group-anagrams/" },
  { title: "Valid Anagram", link: "https://leetcode.com/problems/valid-anagram/" },
  { title: "Longest Common Prefix", link: "https://leetcode.com/problems/longest-common-prefix/" },
  { title: "Count and Say", link: "https://leetcode.com/problems/count-and-say/" },
  { title: "Multiply Strings", link: "https://leetcode.com/problems/multiply-strings/" },
  { title: "Simplify Path", link: "https://leetcode.com/problems/simplify-path/" },
  { title: "Longest Substring with At Most K Distinct Characters", link: "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/" },
  { title: "Minimum Window Substring", link: "https://leetcode.com/problems/minimum-window-substring/" },
  { title: "Substring with Concatenation of All Words", link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/" },
  { title: "Find All Anagrams in a String", link: "https://leetcode.com/problems/find-all-anagrams-in-a-string/" },
  { title: "Reverse Words in a String", link: "https://leetcode.com/problems/reverse-words-in-a-string/" },
  { title: "Reverse Words in a String II", link: "https://leetcode.com/problems/reverse-words-in-a-string-ii/" },
  { title: "Valid Palindrome", link: "https://leetcode.com/problems/valid-palindrome/" },
  { title: "Valid Palindrome II", link: "https://leetcode.com/problems/valid-palindrome-ii/" },
  { title: "Longest Repeating Character Replacement", link: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { title: "String Compression", link: "https://leetcode.com/problems/string-compression/" },
  { title: "Encode and Decode Strings", link: "https://leetcode.com/problems/encode-and-decode-strings/" },
  { title: "Maximum Length of Pair Chain", link: "https://leetcode.com/problems/maximum-length-of-pair-chain/" },
  { title: "Partition Labels", link: "https://leetcode.com/problems/partition-labels/" },
  { title: "Sort Array By Parity", link: "https://leetcode.com/problems/sort-array-by-parity/" },
  { title: "Maximum Swap", link: "https://leetcode.com/problems/maximum-swap/" },
  { title: "Array Partition I", link: "https://leetcode.com/problems/array-partition-i/" },
  { title: "Minimum Size Subarray Sum", link: "https://leetcode.com/problems/minimum-size-subarray-sum/" },
  { title: "Subarray Sum Equals K", link: "https://leetcode.com/problems/subarray-sum-equals-k/" },
  { title: "Maximum Average Subarray I", link: "https://leetcode.com/problems/maximum-average-subarray-i/" },
  { title: "Longest Continuous Increasing Subsequence", link: "https://leetcode.com/problems/longest-continuous-increasing-subsequence/" },
  { title: "Degree of an Array", link: "https://leetcode.com/problems/degree-of-an-array/" },
  { title: "Max Consecutive Ones", link: "https://leetcode.com/problems/max-consecutive-ones/" },
  { title: "Max Consecutive Ones II", link: "https://leetcode.com/problems/max-consecutive-ones-ii/" },
  { title: "Third Maximum Number", link: "https://leetcode.com/problems/third-maximum-number/" },
  { title: "Find All Numbers Disappeared in an Array", link: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/" },
  { title: "Teemo Attacking", link: "https://leetcode.com/problems/teemo-attacking/" },
  { title: "Next Greater Element III", link: "https://leetcode.com/problems/next-greater-element-iii/" },
  { title: "Maximum Product of Three Numbers", link: "https://leetcode.com/problems/maximum-product-of-three-numbers/" },
  { title: "Kth Symbol in Grammar", link: "https://leetcode.com/problems/k-th-symbol-in-grammar/" },
  { title: "Pascal's Triangle", link: "https://leetcode.com/problems/pascals-triangle/" },
  { title: "Pascal's Triangle II", link: "https://leetcode.com/problems/pascals-triangle-ii/" },
  { title: "Triangle", link: "https://leetcode.com/problems/triangle/" },
  { title: "Best Time to Buy and Sell Stock with Cooldown", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/" },
  { title: "Arithmetic Slices", link: "https://leetcode.com/problems/arithmetic-slices/" },
  { title: "Number of Longest Increasing Subsequence", link: "https://leetcode.com/problems/number-of-longest-increasing-subsequence/" },
  { title: "Delete and Earn", link: "https://leetcode.com/problems/delete-and-earn/" },
  { title: "Partition to K Equal Sum Subsets", link: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/" },
  { title: "Predict the Winner", link: "https://leetcode.com/problems/predict-the-winner/" },
  { title: "Stone Game", link: "https://leetcode.com/problems/stone-game/" },
  { title: "Range Sum Query - Immutable", link: "https://leetcode.com/problems/range-sum-query-immutable/" },
  { title: "Range Sum Query 2D - Immutable", link: "https://leetcode.com/problems/range-sum-query-2d-immutable/" },
  { title: "Max Sum of Rectangle No Larger Than K", link: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/" },
  { title: "Count of Smaller Numbers After Self", link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/" },
  { title: "Reverse Pairs", link: "https://leetcode.com/problems/reverse-pairs/" },
  { title: "Queue Reconstruction by Height", link: "https://leetcode.com/problems/queue-reconstruction-by-height/" },
  { title: "Trapping Rain Water II", link: "https://leetcode.com/problems/trapping-rain-water-ii/" },
  { title: "Pour Water", link: "https://leetcode.com/problems/pour-water/" },
  { title: "Falling Squares", link: "https://leetcode.com/problems/falling-squares/" },
  { title: "Kth Smallest Number in Multiplication Table", link: "https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/" },
  { title: "Kth Smallest Product of Two Sorted Arrays", link: "https://leetcode.com/problems/kth-smallest-product-of-two-sorted-arrays/" },
  { title: "Max Chunks To Make Sorted", link: "https://leetcode.com/problems/max-chunks-to-make-sorted/" },
  { title: "Max Chunks To Make Sorted II", link: "https://leetcode.com/problems/max-chunks-to-make-sorted-ii/" },
  { title: "Global and Local Inversions", link: "https://leetcode.com/problems/global-and-local-inversions/" },
  { title: "Swim in Rising Water", link: "https://leetcode.com/problems/swim-in-rising-water/" },
  { title: "Kth Ancestor of a Tree Node", link: "https://leetcode.com/problems/kth-ancestor-of-a-tree-node/" },
  { title: "All Paths From Source to Target", link: "https://leetcode.com/problems/all-paths-from-source-to-target/" },
  { title: "Minimum Number of Days to Disconnect Island", link: "https://leetcode.com/problems/minimum-number-of-days-to-disconnect-island/" },
  { title: "Shortest Path to Get All Keys", link: "https://leetcode.com/problems/shortest-path-to-get-all-keys/" },
  { title: "Shortest Path with Alternating Colors", link: "https://leetcode.com/problems/shortest-path-with-alternating-colors/" },
  { title: "Minimum Fuel Cost to Report to the Capital", link: "https://leetcode.com/problems/minimum-fuel-cost-to-report-to-the-capital/" },
  { title: "Number of Operations to Make Network Connected", link: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/" },
  { title: "Reconstruct Itinerary", link: "https://leetcode.com/problems/reconstruct-itinerary/" },
  { title: "Min Cost to Connect All Points", link: "https://leetcode.com/problems/min-cost-to-connect-all-points/" },
  { title: "Network Delay Time", link: "https://leetcode.com/problems/network-delay-time/" },
  { title: "Find Center of Star Graph", link: "https://leetcode.com/problems/find-center-of-star-graph/" },
  { title: "Maximum Width of Binary Tree", link: "https://leetcode.com/problems/maximum-width-of-binary-tree/" },
  { title: "Even Odd Tree", link: "https://leetcode.com/problems/even-odd-tree/" },
  { title: "Sum of Distances in Tree", link: "https://leetcode.com/problems/sum-of-distances-in-tree/" },
  { title: "Binary Tree Cameras", link: "https://leetcode.com/problems/binary-tree-cameras/" },
  { title: "Amount of Time for Binary Tree to Be Infected", link: "https://leetcode.com/problems/amount-of-time-for-binary-tree-to-be-infected/" },
  { title: "Construct Quad Tree", link: "https://leetcode.com/problems/construct-quad-tree/" },
  { title: "Populating Next Right Pointers in Each Node", link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/" },
  { title: "Populating Next Right Pointers in Each Node II", link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/" },
  { title: "Recover Binary Search Tree", link: "https://leetcode.com/problems/recover-binary-search-tree/" },
  { title: "Binary Search Tree Iterator", link: "https://leetcode.com/problems/binary-search-tree-iterator/" },
  { title: "Delete Node in a BST", link: "https://leetcode.com/problems/delete-node-in-a-bst/" },
  { title: "Insert into a Binary Search Tree", link: "https://leetcode.com/problems/insert-into-a-binary-search-tree/" },
  { title: "Convert Sorted Array to Binary Search Tree", link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/" },
  { title: "Convert Sorted List to Binary Search Tree", link: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/" },
  { title: "Balance a Binary Search Tree", link: "https://leetcode.com/problems/balance-a-binary-search-tree/" },
  { title: "All Elements in Two Binary Search Trees", link: "https://leetcode.com/problems/all-elements-in-two-binary-search-trees/" },
  { title: "Find Mode in Binary Search Tree", link: "https://leetcode.com/problems/find-mode-in-binary-search-tree/" },
  { title: "Minimum Absolute Difference in BST", link: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/" },
  { title: "Minimum Distance Between BST Nodes", link: "https://leetcode.com/problems/minimum-distance-between-bst-nodes/" },
  { title: "Nth Highest Salary", link: "https://leetcode.com/problems/nth-highest-salary/" },
  { title: "Department Top Three Salaries", link: "https://leetcode.com/problems/department-top-three-salaries/" },
  { title: "Second Highest Salary", link: "https://leetcode.com/problems/second-highest-salary/" },
  { title: "Combine Two Tables", link: "https://leetcode.com/problems/combine-two-tables/" },
  { title: "Employees Earning More Than Their Managers", link: "https://leetcode.com/problems/employees-earning-more-than-their-managers/" },
  { title: "Duplicate Emails", link: "https://leetcode.com/problems/duplicate-emails/" },
  { title: "Customers Who Never Order", link: "https://leetcode.com/problems/customers-who-never-order/" },
  { title: "Rising Temperature", link: "https://leetcode.com/problems/rising-temperature/" },
  { title: "Trips and Users", link: "https://leetcode.com/problems/trips-and-users/" },
  { title: "Consecutive Numbers", link: "https://leetcode.com/problems/consecutive-numbers/" },
  { title: "Exchange Seats", link: "https://leetcode.com/problems/exchange-seats/" },
  { title: "Tree Node", link: "https://leetcode.com/problems/tree-node/" },
  { title: "Second Degree Follower", link: "https://leetcode.com/problems/second-degree-follower/" },
  { title: "Shortest Distance in a Line", link: "https://leetcode.com/problems/shortest-distance-in-a-line/" },
  { title: "Human Readable Number of Days", link: "https://leetcode.com/problems/human-readable-number-of-days/" },
  { title: "Longest Substring Without Repeating Characters", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { title: "Merge Two Sorted Lists", link: "https://leetcode.com/problems/merge-two-sorted-lists/" }
   
];

export default STRIVER_DSA_SHEET;